services:
  app:
    build: ./proxy
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./proxy/internal/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: padrinoexperto/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./proxy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./proxy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./proxy/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

volumes:
  redis_data:
  grafana_data: